---
- name: Download Drupal from pantheon download url
  command: chdir=/srv/ curl -o drupal.tar.gz "{{ drupal_code_download_url }}"

- name: Extract archive
  command: chdir=/srv/ /bin/tar xvf drupal.tar.gz creates=/srv/drupal
  
- name: get first aaomembers folder name
  shell: find . -type d -name "aaomembers*" | tail -1 | awk '{ print $0 }'
  register: drupal_folder

- name: output drupal extract folder
  shell: echo {{ drupal_folder }}
  
- name: create drupal directory
  shell: mkdir /srv/drupal

- name: move drupal files from extracted directory drupal_folder to drupal directory
  shell: mv /srv/{{ drupal_folder }}/* .* /srv/drupal/
