---
- name: Download Drupal from pantheon download url
  command: chdir=/srv/ curl -o drupal.tar.gz "{{ drupal_code_download_url }}"

- name: remove old drupal directories
  shell: cd /srv/; rm -rf drupal; rm -rf aaomembers*;
  
- name: Extract archive
  command: chdir=/srv/ /bin/tar xvf drupal.tar.gz #creates=/srv/drupal
  
- name: rename aaomembers extracted folder to drupal
  shell: find . -maxdepth 1 -depth -type d -name 'aaomembers*' -exec mv {} drupal  \; | head -1

- name: Add group "drupal"
  group: name=drupal

- name: Add user "drupal"
  user: name=drupal group=drupal home=/srv/drupal/

- name: Create drupal database
  mysql_db: name={{ d7_db_name }} state=present
  
- name: Create drupal database user
  mysql_user: name={{ d7_db_user }} password={{ d7_db_password }} priv={{ d7_db_name }}.*:ALL host='localhost' state=present
  
#lcl.settings.php is a pantheon thing since we are downloading from pantheon
- name: Copy drupal config file
  template: src=settings.php.y2 dest=/srv/drupal/sites/default/lcl.settings.php
  
- name: Change ownership of drupal installation
  file: path=/srv/drupal/ owner=drupal group=drupal state=directory recurse=yes
