---
- name: remove old drupal directories
  shell: rm -rf drupal; rm -rf aaomembers*;

- name: Download Drupal from pantheon download url
  command: chdir=/srv/ curl -o drupal.tar.gz "{{ drupal_code_download_url }}"

- name: Extract archive
  command: chdir=/srv/ /bin/tar xvf drupal.tar.gz creates=/srv/drupal
  
- name: rename aaomembers extracted folder to drupal
  shell: find . -maxdepth 1 -depth -type d -name 'aaomembers*' -exec mv {} drupal  \; | head -1
